<template>
  <div class="h-full">
    <!-- No Artifact State -->
    <div v-if="!currentArtifact" class="flex h-full items-center justify-center">
      <div class="text-center">
        <i class="fa-solid fa-brackets-curly text-base-content/30"></i>
        <h3 class="mt-4 text-lg font-medium text-base-content/60">No Artifact Selected</h3>
        <p class="mt-2 text-sm text-base-content/40">Artifacts will appear here when generated by the AI</p>
      </div>
    </div>

    <!-- Artifact Content -->
    <div v-else class="flex h-full flex-col">
      <!-- Artifact Header -->
      <div class="flex-shrink-0 border-b border-base-300 pb-4">
        <div class="flex items-start justify-between">
          <div>
            <h4 class="font-semibold">{{ currentArtifact.title || 'Untitled Artifact' }}</h4>
            <p v-if="currentArtifact.description" class="mt-1 text-sm text-base-content/60">
              {{ currentArtifact.description }}
            </p>
          </div>
          <div class="flex items-center gap-1">
            <!-- Copy Button -->
            <button @click="copyArtifact" class="btn btn-ghost btn-sm btn-square" title="Copy to clipboard">
              <i :class="copySuccess ? 'fa-solid fa-check' : 'fa-solid fa-copy'" class="h-4 w-4" />
            </button>

            <!-- Download Button -->
            <button @click="downloadArtifact" class="btn btn-ghost btn-sm btn-square" title="Download file">
              <i class="fa-solid fa-download h-4 w-4" />
            </button>
          </div>
        </div>

        <!-- Artifact Info -->
        <div class="mt-3 flex items-center gap-4 text-xs text-base-content/60">
          <span class="badge badge-ghost badge-sm">
            {{ currentArtifact.type || 'text' }}
          </span>
          <span v-if="currentArtifact.language" class="badge badge-ghost badge-sm">
            {{ currentArtifact.language }}
          </span>
          <span>{{ formatFileSize(currentArtifact.content?.length || 0) }}</span>
        </div>
      </div>

      <!-- Artifact Viewer -->
      <div class="flex-1 overflow-hidden">
        <!-- Code/Text Content -->
        <div v-if="isTextContent" class="h-full">
          <pre class="h-full overflow-auto bg-base-200 p-4 text-sm"><code
            :class="`language-${currentArtifact.language || 'text'}`"
            v-html="highlightedContent"
          ></code></pre>
        </div>

        <!-- Image Content -->
        <img
          v-else-if="currentArtifact.type === 'image'"
          :src="currentArtifact.content"
          :alt="currentArtifact.title || 'Artifact image'"
          class="h-full w-full object-contain"
        />

        <!-- HTML Content -->
        <iframe
          v-else-if="currentArtifact.type === 'html'"
          :srcdoc="currentArtifact.content"
          class="h-full w-full border-0"
          sandbox="allow-scripts"
        ></iframe>

        <!-- JSON Content -->
        <div v-else-if="currentArtifact.type === 'json'" class="h-full">
          <pre class="h-full overflow-auto bg-base-200 p-4 text-sm"><code>{{ formattedJsonContent }}</code></pre>
        </div>

        <!-- Unknown Type -->
        <div v-else class="flex h-full items-center justify-center">
          <div class="text-center">
            <i class="fa-solid fa-file-question mx-auto h-12 w-12 text-base-content/40" />
            <p class="mt-2 text-sm text-base-content/60">Unknown artifact type: {{ currentArtifact.type }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { ref, computed, inject } from 'vue';
  import hljs from 'highlight.js';
  import type { Artifact } from '~/data/models/chat';

  // Inject current artifact from stream context (placeholder for now)
  const currentArtifact = ref<Artifact | null>(null);
  const copySuccess = ref(false);

  const isTextContent = computed(() => {
    const textTypes = ['code', 'text', 'markdown', 'yaml', 'json', 'xml', 'csv'];
    return textTypes.includes(currentArtifact.value?.type || '');
  });

  const highlightedContent = computed(() => {
    if (!currentArtifact.value || !isTextContent.value) return '';

    const language = currentArtifact.value.language || 'text';
    const content = currentArtifact.value.content || '';

    try {
      if (hljs.getLanguage(language)) {
        return hljs.highlight(content, { language }).value;
      } else {
        return hljs.highlightAuto(content).value;
      }
    } catch (error) {
      console.error('Syntax highlighting failed:', error);
      return content;
    }
  });

  const formattedJsonContent = computed(() => {
    if (currentArtifact.value?.type !== 'json') return '';

    try {
      const parsed = JSON.parse(currentArtifact.value.content || '{}');
      return JSON.stringify(parsed, null, 2);
    } catch (error) {
      return currentArtifact.value.content || '';
    }
  });

  function formatFileSize(bytes: number): string {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
  }

  async function copyArtifact() {
    if (!currentArtifact.value?.content) return;

    try {
      await navigator.clipboard.writeText(currentArtifact.value.content);
      copySuccess.value = true;
      setTimeout(() => {
        copySuccess.value = false;
      }, 2000);
    } catch (error) {
      console.error('Failed to copy artifact:', error);
    }
  }

  function downloadArtifact() {
    if (!currentArtifact.value) return;

    const blob = new Blob([currentArtifact.value.content], {
      type: 'text/plain',
    });
    const url = URL.createObjectURL(blob);

    const a = document.createElement('a');
    a.href = url;
    a.download = getFileName();
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  function getFileName() {
    if (!currentArtifact.value) return 'artifact.txt';
    const title = currentArtifact.value.title || 'artifact';
    const language = currentArtifact.value.language;
    const extensions: Record<string, string> = {
      javascript: 'js',
      typescript: 'ts',
      python: 'py',
      html: 'html',
      css: 'css',
      json: 'json',
      markdown: 'md',
      yaml: 'yml',
      xml: 'xml',
      csv: 'csv',
    };

    const ext = extensions[language || ''] || 'txt';
    return `${title.replace(/[^a-zA-Z0-9]/g, '_')}.${ext}`;
  }
</script>

<style scoped>
  pre code {
    font-family: 'Monaco', 'Consolas', 'Courier New', monospace;
    line-height: 1.5;
  }
</style>
